### ISSUE TITLE
可不可以支持  多AndroidManifest.xml 

### ISSUE THREAD

**Issue by Aarthas** [Tangpj/calces-gradle-plugin#1]
app模式 一个AndroidManifest.xml
lib 模式一个AndroidManifest.xml
不共用同一个

**Comment by tangpj** [comment]
在解答这个问题之前，我想知道你用2个AndroidManifest.xml的原因是什么？
app和lib模式的AndroidManifest.xml中主要区别就是配置的入口Activity的不同，如果你的需求合理的话，可以考虑在下个版本中提供这个功能的。

**Comment by Aarthas** [comment]
1. 不同的application，在组件以applicaiton编译的时候需要做某些初始化，而在lib编译的时候，不需要做这些初始化，因为主工程的applicaiton已经初始化了。
2. 我的某些lib工程只有fragment，没有activity，用你库貌似不太好启动，需要做一个壳activity。
   if (mainApp) {
                manifest.srcFile 'src/main/AndroidManifest_RunAlone.xml'
            } else {
                manifest.srcFile 'src/main/AndroidManifest.xml'
                java {
                    //里面有testApplicaiton，testActivity
                    
                    exclude 'debug/**'
                    
                }
            }

目前用你的库，我又做了如上处理

**Comment by tangpj** [comment]
1、你配置Manifest的方法就是传统的组件化的解决方案，Calces的功能之一就是尽可能保持组建的独立性，不需要根据状态来手动管理。
你说的组建以application编译时候需要做的某些初始化应该是指再Manifest中的一些配置，但是当以lib模式运行的时候，主（app）组建中做了同样的配置，例如权限之类的吧？一般情况下，配置写在组建的配置清单中就好了，gardle会自动帮我们合并Manifest文件的。我会认真考虑你这个问题再考虑要不要提供解决方案的，所以我希望你能告诉我，你说的初始化是指什么。如果单单是Manifest配置的问题的话，目前的解决方案是能够支持的。

2、如果单单只有Fragment的库的话，的确是没办法启动的。所以modules里面可以配置一个叫runAloneSuper用来配置单独运行的时候需要的支持库，可以把你的壳Activity放到这个测试支持库里面。不过这是一个测试功能，还没正式发布的。

**Comment by Aarthas** [comment]
组件applicaiton运行的时候，需要配置单独的applicaiton，用于日志的初始化，Http初始化等其他初始化，所以得再配一个manifest。
最后以lib编译的时候，这个单独的applicaiton不需要打包进去。
如果打包的时候组件applicaiton也有一个自定义的applicaiton就会冲突

**Comment by Aarthas** [comment]
如果lib打包的时候组件manifest也有一个自定义的applicaiton就会冲突

**Comment by tangpj** [comment]
我大概懂你的意思了，你所指的应该是manifest中配置的Application的问题。这个我会在后续版本中提供一个配置Application的方案的。
