### ISSUE TITLE
某个工程编译失败

### ISSUE THREAD

**Issue by lisong15** [Tangpj/calces-gradle-plugin#2]
dimens = { auto: true, designPx: 375, scale: 0, corvent small widths: 320,480,720,900,375,360,600,411 }; mipmap = {auto: false, designDensity: xxxhdpi, corvent density: xxhdpi,hdpi,xhdpi }

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':zw_server'.
> For input string: "50.0"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by tangpj** [comment]
编译失败的工程引入了screen插件吗？你这个编译信息看不出来是哪里的问题。

**Comment by lisong15** [comment]
> 编译失败的工程引入了screen插件吗？你这个编译信息看不出来是哪里的问题。

问题找到了，我在dimens里面写了小数，所以报错了。你这边不是支持小数么，有个scale

**Comment by tangpj** [comment]
不支持小数的，因为values里面的dimens是以px为基准标尺来设计的。px是指物理像素点，物理像素点是不支持小数的。scale是指转换后的dp的数值取整格式，不设置或者设置为-1时就会输出小数的。同样的，dp是指虚拟像素点，以我的理解的话，dp也最好以整数的形式表示。
screen这里对px做了限制处理，只支持int值，而dp则可以为小数值（不建议为小数）。但是
dp是表示密度独立像素，dp是屏幕处理的最小尺寸单位了，所以
实际上小数值的dp在系统处理的时候最终也会转换成整数。你可以通过设置sacle来更好的控制转换后的dp值。

lisong15 <notifications@github.com> 于2018年10月15日周一 下午4:51写道：
