### ISSUE TITLE
基准UI 那个是怎么设置的？ 

### ISSUE THREAD

**Issue by zzyycobra1234** [Tangpj/calces-gradle-plugin#3]
例如 我是用1080p的设计搞 我的基准要怎么填？

**Comment by tangpj** [comment]
基准UI是要根据你的设计稿的尺寸来决定的。
就拿手机上的1080P的屏幕来说，它的width应该是等于1080px，height应该是等于1920px。所以这里你的基准要填上1080就可以了。基准尺寸填写的是设计稿的width尺寸，所以基准尺寸你直接查看设计稿的设计屏幕宽度就可以了。

zzyycobra1234 <notifications@github.com> 于2018年10月22日周一 上午11:40写道：
