### ISSUE TITLE
mipmap替换成drawable报错

### ISSUE THREAD

**Issue by thundeGG** [Tangpj/calces-gradle-plugin#4]
drawable{
        designDensity "xxxhdpi"
        mipmapDensity 'xxhdpi','xhdpi','hdpi','mdpi'
        auto true
    }

**Comment by tangpj** [comment]
mipmap{
folder "drawable"
designDensity "xxxhdpi"
mipmapDensity 'xxhdpi','xhdpi','hdpi','mdpi'
auto true
}
应该是改成这样，mipmap这个是没办法动态获取的，为了向下兼容，提供了floder字段来支持图片文件夹的配置

张雷 <notifications@github.com> 于2018年10月22日周一 下午2:47写道：

**Comment by thundeGG** [comment]
感谢大佬
